#Local Host
###Get All Contacts
GET http://localhost:3000/contacts

###Get Contacts by ID
GET http://localhost:3000/contacts/67d0d4e6c1b16a330950bc29

###
GET http://localhost:3000/contacts/67d0d5cfc1b16a330950bc2a

###
GET http://localhost:3000/contacts/67d0d5fdc1b16a330950bc2b

###Create Contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Testing",
    "lastName": "1",
    "email": "testing1@gmail.com",
    "favoriteColor": "red",
    "birthday": "3/29/2025"
}

###Update Contact
PUT http://localhost:3000/contacts/67e833a192c6ffea92c991cb HTTP/1.1
content-type: application/json

{
    "firstName": "Testing",
    "lastName": "2.0",
    "email": "testing2.0@gmail.com",
    "favoriteColor": "blue",
    "birthday": "3/29/2025"
}

###Delete Contact
DELETE http://localhost:3000/contacts/67e833a192c6ffea92c991cb

#Production Routes

###Get all Contacts
GET https://cse341-node-2025.onrender.com/contacts

###Get Contacts by ID

GET https://cse341-node-2025.onrender.com/contacts/67d0d4e6c1b16a330950bc29

###
GET https://cse341-node-2025.onrender.com/contacts/67d0d5cfc1b16a330950bc2a

###
GET https://cse341-node-2025.onrender.com/contacts/67d0d5fdc1b16a330950bc2b

###Create Contact
POST https://cse341-node-2025.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Testing",
    "lastName": "1",
    "email": "testing1@gmail.com",
    "favoriteColor": "red",
    "birthday": "3/29/2025"
}

###Update Contact
PUT https://cse341-node-2025.onrender.com/contacts/67e833a192c6ffea92c991cb HTTP/1.1
content-type: application/json

{
    "firstName": "Testing",
    "lastName": "2.0",
    "email": "testing2.0@gmail.com",
    "favoriteColor": "blue",
    "birthday": "3/29/2025"
}

###Delete Contact
DELETE https://cse341-node-2025.onrender.com/contacts/67e833a192c6ffea92c991cb